[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.117.1",
    "fastmcp>=2.12.4",
    "google-genai>=1.39.1",
    "pandas>=2.3.2",
    "python-multipart>=0.0.20",
]
